name: project-lion-api

on:
  push:
    branches: [ develop ]

env:
  NAME: skdksldk1485
  REPO: project-lion-api
  WORKING-DIRECTORY: .

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.WORKING-DIRECTORY }}
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ env.WORKING-DIRECTORY }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{env.NAME}}/${{env.REPO}}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:

      - name: deploy run
        run: |
          sudo sh /home/ec2-user/run.sh